name: 🐞 Bug Report
description: 创建一个报告以帮助我们改进FloraCore
title: "[Bug]: "
labels: ["bug"]
assignees:
  - flowerinsnowdh
  - xLikeWATCHDOG
body:
  - type: markdown
    attributes:
      value: |
        谢谢你花时间填写这份错误报告
  - type: input
    id: contact
    attributes:
      label: 联系方式
      description: 如果我们需要更多的信息，我们如何与你联系？
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description-bug
    attributes:
      label: 简明扼要地描述该错误是什么
      description: 同时请告诉我们，你期望发生什么？
      placeholder: 告诉我们你看到了什么
    validations:
      required: true
  - type: dropdown
    id: floracore-version
    attributes:
      label: FloraCore 版本
      description: 你运行的是什么版本的FloraCore?
      options:
        - 2.0.4.3
        - 其它版本(请在补充的地方进行补充)
    validations:
      required: true
  - type: dropdown
    id: server-type
    attributes:
      label: 服务器类型
      description: 你是在哪种服务器上运行的FloraCore?
      options:
        - Paper/Bukkit
        - Spigot/Bukkit
        - BungeeCord
        - Waterfall
  - type: textarea
    id: logs
    attributes:
      label: 堆栈错误日志
      description: 如果同时出现错误的话,请给出相关错误的堆栈日志。
      render: shell
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: 用户协议
      description: 通过提交此问题，您同意遵守我们的[用户协议](https://github.com/FloraCore/FloraCore/wiki/%E7%94%A8%E6%88%B7%E5%8D%8F%E8%AE%AE)
      options:
        - label: 我同意遵守FloraCore的用户协议。
          required: true
