# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                       STORAGE SETTINGS                                       | #
# |                                                                                              | #
# |                Controls which storage method FloraCore will use to store data.               | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #
#
# - Possible options:
#
#   |  Remote databases - require connection information to be configured below
#   |=> MySQL
#   |=> MariaDB (preferred over MySQL)
#
#   |  Flat file/local database - don't require any extra configuration
#   |=> H2
#
# - A H2 database is the default option.
storage-method: h2

# The following block defines the settings for remote database storage methods.
#
# - You don't need to touch any of the settings here if you're using a local storage method!
# - The connection detail options are shared between all remote storage types.
data:

  # Define the address and port for the database.
  # - The standard DB engine port is used by default
  #   (MySQL: 3306, PostgreSQL: 5432, MongoDB: 27017)
  # - Specify as "host:port" if differs
  address: localhost

  # The name of the database to store FloraCore data in.
  # - This must be created already. Don't worry about this setting if you're using MongoDB.
  database: minecraft

  # Credentials for the database.
  username: root
  password: ''

  # These settings apply to the MySQL connection pool.
  # - The default values will be suitable for the majority of users.
  # - Do not change these settings unless you know what you're doing!
  pool-settings:

    # Sets the maximum size of the MySQL connection pool.
    # - Basically this value will determine the maximum number of actual
    #   connections to the database backend.
    # - More information about determining the size of connection pools can be found here:
    #   https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
    maximum-pool-size: 10

    # Sets the minimum number of idle connections that the pool will try to maintain.
    # - For maximum performance and responsiveness to spike demands, it is recommended to not set
    #   this value and instead allow the pool to act as a fixed size connection pool.
    #   (set this value to the same as 'maximum-pool-size')
    minimum-idle: 10

    # This setting controls the maximum lifetime of a connection in the pool in milliseconds.
    # - The value should be at least 30 seconds less than any database or infrastructure imposed
    #   connection time limit.
    maximum-lifetime: 1800000 # 30 minutes

    # This setting controls how frequently the pool will 'ping' a connection in order to prevent it
    # from being timed out by the database or network infrastructure, measured in milliseconds.
    # - The value should be less than maximum-lifetime and greater than 30000 (30 seconds).
    # - Setting the value to zero will disable the keepalive functionality.
    keepalive-time: 0

    # This setting controls the maximum number of milliseconds that the plugin will wait for a
    # connection from the pool, before timing out.
    connection-timeout: 5000 # 5 seconds

    # This setting allows you to define extra properties for connections.
    #
    # By default, the following options are set to enable utf8 encoding. (you may need to remove
    # these if you are using PostgreSQL)
    #   useUnicode: true
    #   characterEncoding: utf8
    #
    # You can also use this section to disable SSL connections, by uncommenting the 'useSSL' and
    # 'verifyServerCertificate' options below.
    properties:
      useUnicode: true
      characterEncoding: utf8
      #useSSL: false
      #verifyServerCertificate: false

  # The prefix for all FloraCore SQL tables.
  #
  # - This only applies for remote SQL storage types (MySQL, MariaDB, etc).
  # - Change this if you want to use different tables for different servers.
  table-prefix: 'floracore_'

# Settings for Redis.
# Port 6379 is used by default; set address to "host:port" if differs
redis:
  enabled: false
  address: localhost
  username: ''
  password: ''

# If FloraCore should automatically install translation bundles and periodically update them.
auto-install-translations: true

commands:
  nick:
    rank-permission:
      rank0: "floracore.command.nick.rank.default"
      rank1: "floracore.command.nick.rank.rank1"
      rank2: "floracore.command.nick.rank.rank2"
      rank3: "floracore.command.nick.rank.rank3"
      rank4: "floracore.command.nick.rank.rank4"
      rank5: "floracore.command.nick.rank.rank5"
    rank:
      rank0: "&7DEFAULT"
      rank1: "&aVIP"
      rank2: "&aVIP&6+"
      rank3: "&bMVP"
      rank4: "&bMVP&c+"
      rank5: "&6MVP&c++"
    rank-prefix:
      rank0: "&7"
      rank1: "&a[VIP]"
      rank2: "&a[VIP&6+&a]"
      rank3: "&b[MVP]"
      rank4: "&b[MVP&c+&b]"
      rank5: "&6[MVP&c++&6]"
    sign:
      line1: ""
      line2: "^^^^^^^^^^^^^^^"
      line3: "Enter your"
      line4: "nickname here"
  speed:
    max-fly-speed: 0.8
    max-walk-speed: 0.8

server:
  name: "global"
  type: "lobby"